name: becuser3
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # firebase_auth: ^3.3.16
  firebase_auth: ^4.7.3
  # firebase_core: ^1.15.0
  firebase_core: ^2.15.1
  # cloud_firestore: ^3.1.13
  cloud_firestore: ^4.8.5
  # firebase_storage: ^10.2.14
  firebase_storage: ^11.2.6
  # google_sign_in: ^5.3.0
  google_sign_in: ^6.1.4
  # shared_preferences: ^2.0.15
  shared_preferences: ^2.2.0
  # intl: ^0.17.0
  intl: ^0.18.1
  # get: ^4.6.1
  get: ^4.6.5

  # carousel_slider: ^4.1.1
  carousel_slider: ^4.2.1
  # flutter_phone_direct_caller: ^2.1.1
  flutter_phone_direct_caller: ^2.1.1
  # flutter_email_sender: ^5.1.0
  flutter_email_sender: ^6.0.1
  # url_launcher: ^6.0.20
  url_launcher: ^6.1.12

  # dio: ^4.0.6
  dio: ^5.3.2
  # path_provider: ^2.0.11
  path_provider: ^2.1.0
  # syncfusion_flutter_pdfviewer: ^20.2.36-beta
  syncfusion_flutter_pdfviewer: ^22.2.9
  # open_file: ^3.2.1
  open_file: ^3.3.2
  # pdf: ^3.8.1
  pdf: ^3.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
